# Generated by Django 5.1.6 on 2025-02-26 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField(blank=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('CLT', 'CLT'), ('PJ', 'Pessoa Jurídica'), ('Temporário', 'Temporário'), ('Estágio', 'Estágio')], max_length=20)),
                ('modalidade', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=20)),
                ('local', models.CharField(blank=True, max_length=100)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('free', 'Gratuito'), ('basic', 'Básico'), ('premium', 'Premium'), ('enterprise', 'Empresarial')], max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('vagas_por_dia', models.IntegerField(default=3)),
                ('destaque_cv', models.BooleanField(default=False)),
                ('acesso_antecipado', models.BooleanField(default=False)),
                ('contato_direto', models.BooleanField(default=False)),
                ('notificacoes', models.BooleanField(default=False)),
                ('mentoria', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField()),
                ('ativa', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.plano')),
            ],
            options={
                'db_table': 'jobs_assinatura',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, upload_to='profile_pics')),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('nivel_experiencia', models.CharField(blank=True, choices=[('estagiario', 'Estagiário'), ('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior')], max_length=20)),
                ('resumo', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('curriculo', models.FileField(blank=True, upload_to='curriculos')),
                ('disponivel_mudanca', models.BooleanField(default=False)),
                ('aceita_remoto', models.BooleanField(default=True)),
                ('candidaturas_hoje', models.IntegerField(default=0)),
                ('ultima_candidatura', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
