# Generated by Django 5.1.6 on 2025-02-26 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.plano'),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='assinatura',
            table=None,
        ),
    ]
