# Generated by Django 5.1.6 on 2025-02-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='proxima_cobranca',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='renovacao_automatica',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='ultima_renovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
